# 数据库连接信息

spring:
  application:
    name: Talis-web-management
  datasource:
    url: jdbc:mysql://localhost:3306/talis
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

    # 驼峰命名
    map-underscore-to-camel-case: true


