# 数据库连接信息

spring:
  application:
    name: Talis-web-management
  datasource:
    url: jdbc:mysql://mysql:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

    # 驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug



aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: suny1798
    region: cn-beijing




